const PDFDocument =
    require("pdfkit");

const generatePDF = (report, res) => {

    const doc =
        new PDFDocument({
            margin: 50
        });


    doc.pipe(res);


    doc
        .fontSize(22)
        .text(
            "TaxPal Financial Report",
            {
                align: "center"
            }
        );


    doc.moveDown();


    doc
        .fontSize(12)
        .text(
            `Report Type: ${report.reportType}`
        );


    doc.text(
        `Period: ${report.period}`
    );


    doc.moveDown();


    doc
        .fontSize(16)
        .text("Summary");


    doc.moveDown(0.5);


    doc
        .fontSize(12)
        .text(
            `Total Income: ₹${report.summary.income.toFixed(2)}`
        );


    doc.text(
        `Total Expense: ₹${report.summary.expense.toFixed(2)}`
    );


    doc.text(
        `Net Income: ₹${report.summary.netIncome.toFixed(2)}`
    );


    doc.moveDown();


    doc
        .fontSize(16)
        .text(
            "Expense by Category"
        );


    doc.moveDown(0.5);


    report.categories.forEach(item => {

        doc
            .fontSize(12)
            .text(
                `${item.category}: ₹${item.amount.toFixed(2)} (${item.percentage}%)`
            );

    });


    doc.moveDown();


    doc
        .fontSize(10)
        .text(
            "Generated by TaxPal"
        );


    doc.end();
};


module.exports = {
    generatePDF
};